# Generated by Django 4.2.1 on 2023-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desciption', models.CharField(blank=True, max_length=750, null=True)),
                ('image', models.ImageField(upload_to='product/images')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('in_progress', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
