# Generated by Django 4.2.1 on 2023-05-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_rename_parentcategory_childtheme_parent_theme'),
        ('products', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='child_theme',
            field=models.ForeignKey(blank=True, help_text='If you make this a part of a child theme, \n        if the child theme is deleted so are the posts within it', null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.childtheme'),
        ),
    ]
