# Generated by Django 4.2.1 on 2023-05-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=750, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Select this if you want item to be displayed on website')),
            ],
        ),
        migrations.CreateModel(
            name='ParentTheme',
            fields=[
                ('basetheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='themes.basetheme')),
            ],
            options={
                'verbose_name': 'Parent Theme',
                'verbose_name_plural': 'Parent Themes',
            },
            bases=('themes.basetheme',),
        ),
        migrations.CreateModel(
            name='ChildTheme',
            fields=[
                ('basetheme_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='themes.basetheme')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('parentcategory', models.ForeignKey(blank=True, help_text='Example: Winter child theme would go into seasonal parent theme', null=True, on_delete=django.db.models.deletion.SET_NULL, to='themes.parenttheme')),
            ],
            options={
                'verbose_name': 'Child Theme',
                'verbose_name_plural': 'Child Themes',
            },
            bases=('themes.basetheme',),
        ),
    ]
